name: flutter_ddi
description: "A Flutter package for easy and clean dependency injection management, enhancing code organization and flexibility."
version: 0.1.0
homepage: https://github.com/Willian199/flutter_ddi
issue_tracker: https://github.com/Willian199/flutter_ddi/issues
tags:
  - dependency
  - package
  - version
  - injection
  - management
  - java
  - routes

topics:
  - dependency-injection
  - di
  - injection
  - java
  - routes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dart_ddi: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2