name: flutter_ddi
description: "A Flutter package for easy and clean dependency injection management, enhancing code organization and flexibility."
version: 0.6.0
homepage: https://github.com/Willian199/flutter_ddi
issue_tracker: https://github.com/Willian199/flutter_ddi/issues

tags:
  - dependency
  - package
  - version
  - injection
  - management
  - java
  - routes

topics:
  - dependency-injection
  - di
  - inject
  - java
  - routes

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dart_ddi: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0